name: Build Docker Image for Outline-Zulip Bridge
run-name: ${{ gitea.actor }} is releasing ${{ gitea.repository }}

on:
  push:
    tags:
      - v**
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set tag name
        id: tag
        run: |
          if git describe --tags --exact-match > /dev/null 2>&1; then
            echo "tag=$(git describe --tags)" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: git.caffsoft.dev
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -f release.dockerfile \
            -t git.caffsoft.dev/vueterix/outline-zulip-bridge:latest \
            -t git.caffsoft.dev/vueterix/outline-zulip-bridge:${{ steps.tag.outputs.tag }} .

      - name: Push Docker Images
        run: |
          docker push git.caffsoft.dev/vueterix/outline-zulip-bridge:latest
          if [ "${{ steps.tag.outputs.tag }}" != "latest" ]; then
            docker push git.caffsoft.dev/vueterix/outline-zulip-bridge:${{ steps.tag.outputs.tag }}
          fi
